variables:
  # DEV Environment
  ENVIRONMENT: ADB-IAC-DEV
  RESOURCE_GROUP: dmw2dihadbrg01-learning
  LOCATION: centralindia
  SERVICECONNECTION_RG: learningpipelines
  SUBSCRIPTIONID: "e609b895-8521-4e27-a166-510b517292f5"