parameters:
  - name: environment
    type: string
  - name: serviceConnection
    type: string
  - name: resourceGroup
    type: string
  - name: location
    type: string
  - name: subscription
    type: string
  - name: module
    type: string
  - name: project
    type: string

jobs:
  - deployment: ${{parameters.project}}_env_deployment
    displayName: "${{parameters.project}} Environment Deployment"
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: 'Delete Resource Group'
              inputs:
                azureSubscription: ${{parameters.serviceConnection}}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                az group delete --name ${{parameters.resourceGroup}} --yes