# Pipeline that destroys MME resource group and all its resources.

trigger:
- none

variables:
- template: ../configurations/configuration.variables.yml
- template: ../configurations/prjtco/configuration-infra-DEV.variables.yml # DEV as default env

pool:
  vmImage: $(VM_VERSION)

stages:
# Destroy DEV Environment
- stage: destroyinfra_dev
  displayName: 'Delete DEV Environment'
  variables:
  - template: ../configurations/prjmme/configuration-infra-DEV.variables.yml
  jobs:
  - template: templates/delete-env-infra.template.yml
    parameters:
      environment: MME-IAC-DEV
      serviceConnection: $(SERVICECONNECTION_RG)
      resourceGroup: $(RESOURCE_GROUP)
      location: $(LOCATION)
      subscription: $(SUBSCRIPTIONID)
      module: 'prj'
      project: 'MME'