# Pipeline that deploys the Databricks infrastructure 

trigger:
  branches:
    include:
    - deployment\modules\prj\parameters\parameters.MME-IAC-DEV.json

variables:
- template: ../configurations/configuration.variables.yml
- template: ../configurations/prjmme/configuration-infra-DEV.variables.yml # DEV as default env

pool:
  vmImage: $(VM_VERSION)

stages:

####################
##  BUILD INFRA  ##
####################

# Lint the Bicep file.
- stage: buildinfra
  displayName: 'Build Environment'
  jobs: 
  - template: templates/run-code-lint.template.yml
    parameters:
      module: 'prj'

####################
##  DEPLOY INFRA  ##
####################

# Deploy DEV Environment
- stage: deployinfra_dev
  displayName: 'Deploy DEV Environment'
  dependsOn: buildinfra
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
  - template: ../configurations/prjmme/configuration-infra-DEV.variables.yml
  jobs:
  - template: templates/deploy-env-infra.template.yml
    parameters:
      environment: IOT-IAC-DEV
      serviceConnection: $(SERVICECONNECTION_RG)
      resourceGroup: $(RESOURCE_GROUP)
      location: $(LOCATION)
      subscription: $(SUBSCRIPTIONID)
      module: 'prj'
      project: 'MME'